# -----------------------------------------------
# MySQL Database Configuration
# -----------------------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/patient_queue_db
spring.datasource.username=root
spring.datasource.password=YASHDABHADE997

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# App Info
spring.application.name=Patient-Queue-Management-System
server.port=8080